import type { Avatar } from "@/types";

export function generateLua(avatar: Avatar) {
    return [
        `--------------------------------------`,
        `-- This file is generated by --`,
        `-- https://pfg.pw/figura-action-wheel-editor`,
        ``,
        `-- Edit it at the website.`,
        `--------------------------------------`,
        ``,
        ``,
        `-- %__DATA_MARKER__%`,
        JSON.stringify(avatar, null, 2).split("\n").map(l => "-- " + l).join("\n"),
        `-- %__DATA_MARKER__%`,
        ``
    ].join("\n");
}

export function parseLua(source: string): Avatar {
    const dmsplit = source.split("-- %__DATA_MARKER__%");
    if(dmsplit.length !== 3) throw new Error("Invalid or corrupted source");
    return JSON.parse(dmsplit[1].split("\n").map(l => l.startsWith("--") ? l.slice(2) : l).join("\n"));
}